[package]
name = "stfu-backend"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
async-std = { version = "1.6.5", features = ["tokio02", "attributes"] }
ctrlc = "3.1.7"
juniper = "0.14.2"
juniper_rocket = "0.5.2"
log = "0.4.11"
pretty_env_logger = "0.4.0"
rarity-permission-calculator = { branch = "main", git = "https://github.com/rarity-rs/permission-calculator" }
rocket = "0.4.5"
rocket_cors = "0.5.2"
# FIXME: move to tagged release once viable
twilight-cache-inmemory = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-embed-builder = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-gateway = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-http = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-mention = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-model = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-standby = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
# twilight-oauth2 = { branch = "oauth2", git = "https://github.com/vivian/twilight" } TODO: wait for merge to stable
serde_json = { version = "1.0.59", optional = true }

[features]
generate_schema = ["serde_json"]
