[package]
name = "stfu-backend"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
async-std = { version = "1.6.5", features = ["tokio02", "attributes", "unstable"] }
ctrlc = "3.1.7"
futures = "0.3.6"
juniper = { branch = "master", git = "https://github.com/graphql-rust/juniper" }
juniper_rocket_async = { branch = "master", git = "https://github.com/graphql-rust/juniper" }
log = "0.4.11"
pretty_env_logger = "0.4.0"
reqwest = "0.10.8"
rocket = { branch = "master", git = "https://github.com/SergioBenitez/Rocket", features = ["secrets"] }
# rocket_cors = { branch = "master", git = "https://github.com/lawliet89/rocket_cors" }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
urlencoding = "1.1.1"

# Twilight mess
twilight-permission-calculator = { branch = "branding", git = "https://github.com/dusterthefirst/permission-calculator" }
twilight-model_v1 = { package = "twilight-model", version = "0.1" }
twilight-oauth2 = { branch = "trunk", git = "https://github.com/twilight-rs/oauth2" }# TODO: merge to stable
# FIXME: move to tagged release once viable
twilight-cache-inmemory = "0.2.0-beta"
twilight-embed-builder = "0.2.0-beta"
twilight-gateway = "0.2.0-beta"
twilight-http = "0.2.0-beta"
twilight-mention = "0.2.0-beta"
twilight-model = "0.2.0-beta"
twilight-standby = "0.2.0-beta"

[features]
generate_schema = []
