[package]
name = "backend"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.5", features = ["tokio02", "attributes"] }
serenity = { version = "0.9.0-rc.2", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "rustls_backend",
    "utils",
] }
juniper = "0.14.2"
juniper_rocket = "0.5.2"
rocket = "0.4.5"
pretty_env_logger = "0.4.0"
log = "0.4.11"