[package]
name = "stfu-backend"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
async-std = { version = "1.6.5", features = ["tokio02", "attributes"] }
ctrlc = "3.1.6"
juniper = "0.14.2"
juniper_rocket = "0.5.2"
log = "0.4.11"
pretty_env_logger = "0.4.0"
rarity-permission-calculator = { branch = "main", git = "https://github.com/rarity-rs/permission-calculator" }
rocket = "0.4.5"
rocket_cors = "0.5.2"
twilight-cache-inmemory = "0.1.1"
twilight-embed-builder = "0.1.0"
twilight-gateway = "0.1.3"
twilight-http = "0.1.6"
twilight-mention = "0.1.1"
twilight-model = "0.1.3"
twilight-standby = "0.1.1"
serde_json = { version = "1.0.58", optional = true }

[features]
generate_schema = ["serde_json"]
